lsi: false
title: Ayush Dhar Dubey
author: Ayush Dhar Dubey
email: mailaddubey@gmail.com
description: >
  Notes from a wandering mind.
  A small corner of the internet where I write about the things that keep me curious.
baseurl: ""
url: "https://ayushdhardubey.github.io"

github_username:  AyushDharDubey
linkedin_username: ayushdhardubey

permalink: /:categories/:year/:month/:day/:title/
theme: minima
timezone: Asia/Kolkata
header_pages:
  - about.md
  - library.md
